"""gen_hls_weights.py — emit the HLS weight ROM header `hls/src/c7_weights.hpp` from deploy_weights.npz.

The real on-chip weights, laid out to match the faithful HLS arrays (c7_audio_core.hpp / c7_video.hpp).
Conv / linear (MAC) operands -> `wgt_t` (ap_fixed<16,5>); inline BN/in_norm affine (s,b), PReLU slopes and
folded conv biases -> `bn_t` (ap_fixed<32,16>, wide enough for the in_norm scale ~102). Values are emitted at
full float32 precision (%.9g) so the HLS type truncates the *same* float the emulator's quantizers truncate
-> emulator and silicon land on the same fixed-point grid. Regenerate after retraining:

    python tools/export_weights.py            # best.pt -> deploy_weights.npz
    python tools/gen_hls_weights.py           # npz -> hls/src/c7_weights.hpp
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np


def fmt(x):
    return "%.9g" % np.float32(x)


def emit_array(name, ctype, arr):
    """Emit `static const ctype name[d0][d1]... = { nested braces };`."""
    arr = np.asarray(arr, dtype=np.float32)
    dims = "".join(f"[{d}]" for d in arr.shape)

    def rec(a):
        if a.ndim == 1:                                  # innermost row on one (short) line
            return "{" + ",".join(fmt(v) for v in a) + "}"
        return "{" + ",\n".join(rec(sub) for sub in a) + "}"  # newline-separate higher dims (lexer-friendly)

    return f"static const {ctype} {name}{dims} = {rec(arr)};\n"


def main() -> int:
    repo = Path(__file__).resolve().parents[1]
    ap = argparse.ArgumentParser()
    ap.add_argument("--npz", default=str(repo / "experiments/p2-c7-full/deploy_weights.npz"))
    ap.add_argument("--out", default=str(repo / "hls/src/c7_weights.hpp"))
    args = ap.parse_args()

    z = np.load(args.npz)
    NBLK = int(z["meta_NBLK"])

    def stack(key):  # stack per-block arrays -> [NBLK][...]
        return np.stack([z[f"t{i}_{key}"] for i in range(NBLK)], axis=0)

    # (c_name, c_type, numpy array in HLS layout)
    items = [
        # ---- audio: encoder / decoder ----
        ("Wenc", "wgt_t", z["enc_w"]),                 # [N][L]
        ("Wdec", "wgt_t", z["dec_w"]),                 # [N][L]
        # ---- in_norm (inline affine) + bottleneck ----
        ("innorm_s", "bn_t", z["innorm_s"]),           # [N]
        ("innorm_b", "bn_t", z["innorm_b"]),           # [N]
        ("Wbn", "wgt_t", z["bn_W"]),                   # [N][B]  ([n][b])
        # ---- TCN blocks ----
        ("Win",  "wgt_t", stack("in_w")),              # [NBLK][B][H]  ([b][c])
        ("pr1",  "bn_t",  stack("pr1")),               # [NBLK][H]
        ("bn1_s", "bn_t", stack("bn1_s")),
        ("bn1_b", "bn_t", stack("bn1_b")),
        ("Wdw",  "wgt_t", stack("dw_w")),              # [NBLK][H][KD]
        ("pr2",  "bn_t",  stack("pr2")),
        ("bn2_s", "bn_t", stack("bn2_s")),
        ("bn2_b", "bn_t", stack("bn2_b")),
        ("Wout", "wgt_t", stack("out_w")),             # [NBLK][H][B]  ([c][b])
        # ---- mask ----
        ("Wmask", "wgt_t", z["mask_W"]),               # [B][N]  ([b][n])
        # ---- video encoder ----
        ("v_c0_w", "wgt_t", z["v_c0_w"][:, 0, :, :]),  # [C0][7][7] (squeeze in-ch=1)
        ("v_c0_b", "bn_t", z["v_c0_b"]),               # [C0]
        ("v_dw1_w", "wgt_t", z["v_dw1_w"]), ("v_pw1_w", "wgt_t", z["v_pw1_w"]), ("v_pw1_b", "bn_t", z["v_pw1_b"]),
        ("v_sc1_w", "wgt_t", z["v_sc1_w"]), ("v_sc1_b", "bn_t", z["v_sc1_b"]),
        ("v_dw2_w", "wgt_t", z["v_dw2_w"]), ("v_pw2_w", "wgt_t", z["v_pw2_w"]), ("v_pw2_b", "bn_t", z["v_pw2_b"]),
        ("v_sc2_w", "wgt_t", z["v_sc2_w"]), ("v_sc2_b", "bn_t", z["v_sc2_b"]),
        ("v_dw3_w", "wgt_t", z["v_dw3_w"]), ("v_pw3_w", "wgt_t", z["v_pw3_w"]), ("v_pw3_b", "bn_t", z["v_pw3_b"]),
        ("v_sc3_w", "wgt_t", z["v_sc3_w"]), ("v_sc3_b", "bn_t", z["v_sc3_b"]),
        ("v_fp_w", "wgt_t", z["v_fp_w"]),              # [C][C][2][2]
        ("v_fp_b", "bn_t", z["v_fp_b"]),               # [C]
        ("v_tp_w", "wgt_t", z["v_tp_w"]),              # [C][C]  ([o][i])
        ("v_tp_b", "bn_t", z["v_tp_b"]),               # [C]
        ("vproj_w", "wgt_t", z["vproj_w"]),            # [B][C]  ([b][c])
        ("vproj_b", "bn_t", z["vproj_b"]),             # [B]
    ]

    lines = [
        "// c7_weights.hpp — GENERATED by tools/gen_hls_weights.py from deploy_weights.npz. DO NOT EDIT.",
        "// Real trained C7 weights (p2-c7-full/best.pt), BN-folded + laid out for the faithful HLS design.",
        "// wgt_t = MAC operands; bn_t = inline BN/in_norm affine, PReLU slopes, folded conv biases.",
        "#ifndef C7_WEIGHTS_HPP",
        "#define C7_WEIGHTS_HPP",
        '#include "c7_types.hpp"',
        "namespace c7 { namespace wts {",
        "using cfg::N; using cfg::L; using cfg::B; using cfg::H; using cfg::NBLK; using cfg::KD;",
        "",
    ]
    total = 0
    for name, ctype, arr in items:
        lines.append(emit_array(name, ctype, arr))
        total += int(np.asarray(arr).size)
    lines += ["", "} }  // namespace c7::wts", "#endif  // C7_WEIGHTS_HPP", ""]

    out = Path(args.out)
    out.write_text("\n".join(lines), encoding="utf-8")
    sz = out.stat().st_size
    print(f"wrote {out}  ({len(items)} arrays, {total} scalars, {sz/1e6:.2f} MB)")
    return 0


if __name__ == "__main__":
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass
    sys.exit(main())
