"""score_candidates.py — emit the Phase-1 candidate scoring table.

Runs every candidate through the validated working-set model and produces the
*approach x peak-activation x fit x quality-risk x effort* table that the owner reviews to pick the
2-3 directions for Phase 2. Writes results/candidate_scoring.md and prints to console.
"""
from __future__ import annotations

import sys
try:
    sys.stdout.reconfigure(encoding="utf-8")
except (AttributeError, OSError):
    pass

from pathlib import Path
from candidates import all_candidates
from working_set import BRAM18_BUDGET

HERE = Path(__file__).parent
OUT = HERE / "results" / "candidate_scoring.md"

REFERENCE_PEAK_MB = 2.4   # validated audio peak-live of the reference U-Net


def main() -> int:
    cands = all_candidates()

    # Console table
    print("=" * 100)
    print("PHASE 1 — CANDIDATE SCORING (peak-live activation via the validated working-set model)")
    print("=" * 100)
    hdr = (f"{'key':<4} {'approach':<34} {'fam':<5} {'peak-live':>10} {'audio':>6} {'sys':>5} "
           f"{'fit':<14} {'reuse':<6} {'risk':<9} {'effort'}")
    print(hdr); print("-" * len(hdr))
    def status(c):
        return "out:D-2" if not c.in_scope else ("lever" if c.combinable_lever else "")
    for c in cands:
        print(f"{c.key:<4} {c.name[:34]:<34} {c.family:<5} "
              f"{c.peak_live_mb:>8.2f}MB {c.bram_pct:>5.0f}% {c.system_bram_pct:>4.0f}% {c.fit_verdict:<14} "
              f"{'yes' if c.reuses_weights else 'no':<6} {c.quality_risk.split('(')[0].strip():<9} "
              f"{c.effort:<14} {status(c)}")
    print(f"\n(sys = audio peak-live + ~{int(__import__('candidates').SHARED_OVERHEAD_PCT)}% shared "
          f"video+fusion+weights overhead; fit verdict is on the whole single-config system.)")

    # Markdown report
    from candidates import SHARED_OVERHEAD_PCT
    lines = []
    lines.append("# Phase 1 — candidate scoring table\n")
    lines.append(
        f"Generated by `analysis/score_candidates.py` from the **validated** working-set model "
        f"(see `results/baseline_validation.md`). `peak-live` = peak simultaneously-live audio "
        f"activation (the metric validated against the reference). `audio%` = rough single-pool BRAM% "
        f"of that peak on the ZU48DR (budget {BRAM18_BUDGET} RAMB18). `sys%` = audio% plus the "
        f"~{SHARED_OVERHEAD_PCT:.0f}% shared overhead every single-config design also carries (video "
        f"encoder ~38% + fusion ~32% + weight/working residue, lightly deduped). **The fit verdict is "
        f"on `sys%` — the whole system co-resident in one static configuration.**\n")
    lines.append("| key | approach | family | axis | peak-live | audio% | sys% | fit | status | reuses weights | quality risk | effort |")
    lines.append("|---|---|---|---|---:|---:|---:|---|---|:--:|---|---|")
    for c in cands:
        st = "out (D-2)" if not c.in_scope else ("lever" if c.combinable_lever else "—")
        lines.append(f"| {c.key} | {c.name} | {c.family} | {c.axis} | {c.peak_live_mb:.2f} MB | "
                     f"{c.bram_pct:.0f}% | {c.system_bram_pct:.0f}% | {c.fit_verdict} | {st} | "
                     f"{'✅' if c.reuses_weights else '—'} | {c.quality_risk} | {c.effort} |")
    lines.append("\n## Notes per candidate\n")
    for c in cands:
        lines.append(f"- **{c.key} {c.name}** ({c.axis}): {c.notes}")

    lines.append("\n## Reading the table\n")
    lines.append(f"- The reference U-Net audio peak-live is **{REFERENCE_PEAK_MB} MB ~= 75% BRAM by "
                 "itself**; add the shared video+fusion overhead and **C0/C6 land at ~140% — they DO "
                 "NOT FIT.** This is the sharpened, model-backed form of the validated finding: "
                 "**time-multiplexing/pooling the same U-Net (Axis 3 alone) cannot fit the system.**")
    lines.append("- **Bounding the live temporal extent works**: tiling/streaming (C4/C1) and "
                 "single-resolution masking (C2/C7) drop peak-live by 6–25x into comfortable-fit territory.")
    lines.append("- **The cleanest time-domain attack on the root cause is C7** (Conv-TasNet-style): it "
                 "has **no multi-resolution U-Net skips at all**, so the skip-residency wall simply does "
                 "not exist — without leaving the time domain (D-2).")
    lines.append("- **Decision context**: D-2 = time-domain only, so **C3 (STFT) is out of scope** "
                 "(kept for record). C8/C9 are BRAM-reclaim *levers* — best combined with a base "
                 "architecture, not run standalone.")
    lines.append("\n## Phase-2 set (owner D-8 + analysis)\n")
    lines.append("1. **C4 Tiled U-Net** — lowest-risk fit, reuses the trained 0.37M model; the safe anchor / control.")
    lines.append("2. **C2 Streaming TCN** — strong circuits novelty (O(state) dataflow), distillable, time-domain.")
    lines.append("3. **C7 Conv-TasNet-style mask** — removes the U-Net skip wall (root cause) while staying "
                 "time-domain; proven SE quality. The headline new candidate.")
    lines.append("\n*C5 (DDR-staged) kept as the Plan-B control; C8/C9 (recompute/compressed skip) are "
                 "levers to combine if a base architecture needs more headroom; C6 documents that "
                 "schedule-only is not enough; C3 parked by D-2.*")
    lines.append("\n> These peak-live numbers are analytical screening (Phase 1). Phase 2 trains small "
                 "versions to put **quality** on the same axis and produce the quality-vs-working-set "
                 "Pareto frontier before any HLS.")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"\nWrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
